# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: /home/hayes/
email: me@hayespotter.com
description: >
  Words, images, links, and other useless ramblings
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.hayespotter.com" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: 'Hayes Potter'
bio: >
  Web developer, systems technician, security analyst, car enthusiast, apple fan boy, helix follower.
author_image: "/assets/images/author.jpg"
twitter_username: 
github_username:  hayespotter

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
